import React from "react";

export const dataDb = [
  {
    bodyPart: "waist",
    equipment: "body weight",
    gifUrl: "http://d205bpvrqc9yn1.cloudfront.net/0001.gif",
    id: "0001",
    name: "3/4 sit-up",
  },
  {
    bodyPart: "waist",
    equipment: "body weight",
    gifUrl: "http://d205bpvrqc9yn1.cloudfront.net/0002.gif",
    id: "0002",
    name: "45° side bend",
  },
  {
    bodyPart: "waist",
    equipment: "body weight",
    gifUrl: "http://d205bpvrqc9yn1.cloudfront.net/0003.gif",
    id: "0003",
    name: "air bike",
  },
  {
    bodyPart: "upper legs",
    equipment: "body weight",
    gifUrl: "http://d205bpvrqc9yn1.cloudfront.net/1512.gif",
    id: "1512",
    name: "all fours squad stretch",
  },
  {
    bodyPart: "waist",
    equipment: "body weight",
    gifUrl: "http://d205bpvrqc9yn1.cloudfront.net/0006.gif",
    id: "0006",
    name: "alternate heel touchers",
  },
  {
    bodyPart: "back",
    equipment: "cable",
    gifUrl: "http://d205bpvrqc9yn1.cloudfront.net/0007.gif",
    id: "0007",
    name: "alternate lateral pulldown",
  },
  {
    bodyPart: "lower legs",
    equipment: "body weight",
    gifUrl: "http://d205bpvrqc9yn1.cloudfront.net/1368.gif",
    id: "1368",
    name: "ankle circles",
  },
  {
    bodyPart: "back",
    equipment: "body weight",
    gifUrl: "http://d205bpvrqc9yn1.cloudfront.net/3293.gif",
    id: "3293",
    name: "archer pull up",
  },
  {
    bodyPart: "chest",
    equipment: "body weight",
    gifUrl: "http://d205bpvrqc9yn1.cloudfront.net/3294.gif",
    id: "3294",
    name: "archer push up",
  },
  {
    bodyPart: "waist",
    equipment: "body weight",
    gifUrl: "http://d205bpvrqc9yn1.cloudfront.net/2355.gif",
    id: "2355",
    name: "arm slingers hanging bent knee legs",
  },
  {
    bodyPart: "waist",
    equipment: "body weight",
    gifUrl: "http://d205bpvrqc9yn1.cloudfront.net/2333.gif",
    id: "2333",
    name: "arm slingers hanging straight legs",
  },
  {
    bodyPart: "upper legs",
    equipment: "body weight",
    gifUrl: "http://d205bpvrqc9yn1.cloudfront.net/3214.gif",
    id: "3214",
    name: "arms apart circular toe touch (male)",
  },
  {
    bodyPart: "waist",
    equipment: "body weight",
    gifUrl: "http://d205bpvrqc9yn1.cloudfront.net/3204.gif",
    id: "3204",
    name: "arms overhead full sit-up (male)",
  },
  {
    bodyPart: "chest",
    equipment: "leverage machine",
    gifUrl: "http://d205bpvrqc9yn1.cloudfront.net/0009.gif",
    id: "0009",
    name: "assisted chest dip (kneeling)",
  },
  {
    bodyPart: "waist",
    equipment: "assisted",
    gifUrl: "http://d205bpvrqc9yn1.cloudfront.net/0011.gif",
    id: "0011",
    name: "assisted hanging knee raise",
  },
  {
    bodyPart: "waist",
    equipment: "assisted",
    gifUrl: "http://d205bpvrqc9yn1.cloudfront.net/0010.gif",
    id: "0010",
    name: "assisted hanging knee raise with throw down",
  },
  {
    bodyPart: "lower legs",
    equipment: "assisted",
    gifUrl: "http://d205bpvrqc9yn1.cloudfront.net/1708.gif",
    id: "1708",
    name: "assisted lying calves stretch",
  },
  {
    bodyPart: "upper legs",
    equipment: "assisted",
    gifUrl: "http://d205bpvrqc9yn1.cloudfront.net/1709.gif",
    id: "1709",
    name: "assisted lying glutes stretch",
  },
  {
    bodyPart: "upper legs",
    equipment: "assisted",
    gifUrl: "http://d205bpvrqc9yn1.cloudfront.net/1710.gif",
    id: "1710",
    name: "assisted lying gluteus and piriformis stretch",
  },
  {
    bodyPart: "waist",
    equipment: "assisted",
    gifUrl: "http://d205bpvrqc9yn1.cloudfront.net/0012.gif",
    id: "0012",
    name: "assisted lying leg raise with lateral throw down",
  },
  {
    bodyPart: "waist",
    equipment: "assisted",
    gifUrl: "http://d205bpvrqc9yn1.cloudfront.net/0013.gif",
    id: "0013",
    name: "assisted lying leg raise with throw down",
  },
  {
    bodyPart: "waist",
    equipment: "medicine ball",
    gifUrl: "http://d205bpvrqc9yn1.cloudfront.net/0014.gif",
    id: "0014",
    name: "assisted motion russian twist",
  },
  {
    bodyPart: "back",
    equipment: "leverage machine",
    gifUrl: "http://d205bpvrqc9yn1.cloudfront.net/0015.gif",
    id: "0015",
    name: "assisted parallel close grip pull-up",
  },
  {
    bodyPart: "upper legs",
    equipment: "assisted",
    gifUrl: "http://d205bpvrqc9yn1.cloudfront.net/0016.gif",
    id: "0016",
    name: "assisted prone hamstring",
  },
  {
    bodyPart: "upper legs",
    equipment: "assisted",
    gifUrl: "http://d205bpvrqc9yn1.cloudfront.net/1713.gif",
    id: "1713",
    name: "assisted prone lying quads stretch",
  },
  {
    bodyPart: "waist",
    equipment: "assisted",
    gifUrl: "http://d205bpvrqc9yn1.cloudfront.net/1714.gif",
    id: "1714",
    name: "assisted prone rectus femoris stretch",
  },
  {
    bodyPart: "back",
    equipment: "leverage machine",
    gifUrl: "http://d205bpvrqc9yn1.cloudfront.net/0017.gif",
    id: "0017",
    name: "assisted pull-up",
  },
  {
    bodyPart: "chest",
    equipment: "assisted",
    gifUrl: "http://d205bpvrqc9yn1.cloudfront.net/1716.gif",
    id: "1716",
    name: "assisted seated pectoralis major stretch with stability ball",
  },
  {
    bodyPart: "upper legs",
    equipment: "assisted",
    gifUrl: "http://d205bpvrqc9yn1.cloudfront.net/1712.gif",
    id: "1712",
    name: "assisted side lying adductor stretch",
  },
  {
    bodyPart: "waist",
    equipment: "assisted",
    gifUrl: "http://d205bpvrqc9yn1.cloudfront.net/1758.gif",
    id: "1758",
    name: "assisted sit-up",
  },
  {
    bodyPart: "back",
    equipment: "leverage machine",
    gifUrl: "http://d205bpvrqc9yn1.cloudfront.net/1431.gif",
    id: "1431",
    name: "assisted standing chin-up",
  },
  {
    bodyPart: "back",
    equipment: "leverage machine",
    gifUrl: "http://d205bpvrqc9yn1.cloudfront.net/1432.gif",
    id: "1432",
    name: "assisted standing pull-up",
  },
  {
    bodyPart: "upper arms",
    equipment: "assisted",
    gifUrl: "http://d205bpvrqc9yn1.cloudfront.net/0018.gif",
    id: "0018",
    name: "assisted standing triceps extension (with towel)",
  },
  {
    bodyPart: "upper arms",
    equipment: "leverage machine",
    gifUrl: "http://d205bpvrqc9yn1.cloudfront.net/0019.gif",
    id: "0019",
    name: "assisted triceps dip (kneeling)",
  },
  {
    bodyPart: "chest",
    equipment: "leverage machine",
    gifUrl: "http://d205bpvrqc9yn1.cloudfront.net/2364.gif",
    id: "2364",
    name: "assisted wide-grip chest dip (kneeling)",
  },
  {
    bodyPart: "cardio",
    equipment: "body weight",
    gifUrl: "http://d205bpvrqc9yn1.cloudfront.net/3220.gif",
    id: "3220",
    name: "astride jumps (male)",
  },
  {
    bodyPart: "cardio",
    equipment: "body weight",
    gifUrl: "http://d205bpvrqc9yn1.cloudfront.net/3672.gif",
    id: "3672",
    name: "back and forth step",
  },
  {
    bodyPart: "back",
    equipment: "stability ball",
    gifUrl: "http://d205bpvrqc9yn1.cloudfront.net/1314.gif",
    id: "1314",
    name: "back extension on exercise ball",
  },
  {
    bodyPart: "back",
    equipment: "body weight",
    gifUrl: "http://d205bpvrqc9yn1.cloudfront.net/3297.gif",
    id: "3297",
    name: "back lever",
  },
  {
    bodyPart: "back",
    equipment: "body weight",
    gifUrl: "http://d205bpvrqc9yn1.cloudfront.net/1405.gif",
    id: "1405",
    name: "back pec stretch",
  },
  {
    bodyPart: "upper legs",
    equipment: "body weight",
    gifUrl: "http://d205bpvrqc9yn1.cloudfront.net/1473.gif",
    id: "1473",
    name: "backward jump",
  },
  {
    bodyPart: "upper legs",
    equipment: "body weight",
    gifUrl: "http://d205bpvrqc9yn1.cloudfront.net/0020.gif",
    id: "0020",
    name: "balance board",
  },
  {
    bodyPart: "upper arms",
    equipment: "band",
    gifUrl: "http://d205bpvrqc9yn1.cloudfront.net/0968.gif",
    id: "0968",
    name: "band alternating biceps curl",
  },
  {
    bodyPart: "waist",
    equipment: "band",
    gifUrl: "http://d205bpvrqc9yn1.cloudfront.net/0969.gif",
    id: "0969",
    name: "band alternating v-up",
  },
  {
    bodyPart: "back",
    equipment: "band",
    gifUrl: "http://d205bpvrqc9yn1.cloudfront.net/0970.gif",
    id: "0970",
    name: "band assisted pull-up",
  },
  {
    bodyPart: "waist",
    equipment: "band",
    gifUrl: "http://d205bpvrqc9yn1.cloudfront.net/0971.gif",
    id: "0971",
    name: "band assisted wheel rollerout",
  },
  {
    bodyPart: "chest",
    equipment: "band",
    gifUrl: "http://d205bpvrqc9yn1.cloudfront.net/1254.gif",
    id: "1254",
    name: "band bench press",
  },
  {
    bodyPart: "upper legs",
    equipment: "band",
    gifUrl: "http://d205bpvrqc9yn1.cloudfront.net/0980.gif",
    id: "0980",
    name: "band bent-over hip extension",
  },
  {
    bodyPart: "waist",
    equipment: "band",
    gifUrl: "http://d205bpvrqc9yn1.cloudfront.net/0972.gif",
    id: "0972",
    name: "band bicycle crunch",
  },
  {
    bodyPart: "back",
    equipment: "band",
    gifUrl: "http://d205bpvrqc9yn1.cloudfront.net/0974.gif",
    id: "0974",
    name: "band close-grip pulldown",
  },
  {
    bodyPart: "upper arms",
    equipment: "band",
    gifUrl: "http://d205bpvrqc9yn1.cloudfront.net/0975.gif",
    id: "0975",
    name: "band close-grip push-up",
  },
  {
    bodyPart: "upper arms",
    equipment: "band",
    gifUrl: "http://d205bpvrqc9yn1.cloudfront.net/0976.gif",
    id: "0976",
    name: "band concentration curl",
  },
  {
    bodyPart: "back",
    equipment: "band",
    gifUrl: "http://d205bpvrqc9yn1.cloudfront.net/3117.gif",
    id: "3117",
    name: "band fixed back close grip pulldown",
  },
  {
    bodyPart: "back",
    equipment: "band",
    gifUrl: "http://d205bpvrqc9yn1.cloudfront.net/3116.gif",
    id: "3116",
    name: "band fixed back underhand pulldown",
  },
  {
    bodyPart: "chest",
    equipment: "barbell",
    gifUrl: "http://d205bpvrqc9yn1.cloudfront.net/0025.gif",
    id: "0025",
    name: "barbell bench press",
  },
  {
    bodyPart: "waist",
    equipment: "body weight",
    gifUrl: "http://d205bpvrqc9yn1.cloudfront.net/0001.gif",
    id: "0001",
    name: "3/4 sit-up",
  },
  {
    bodyPart: "waist",
    equipment: "body weight",
    gifUrl: "http://d205bpvrqc9yn1.cloudfront.net/0002.gif",
    id: "0002",
    name: "45° side bend",
  },
  {
    bodyPart: "waist",
    equipment: "body weight",
    gifUrl: "http://d205bpvrqc9yn1.cloudfront.net/0003.gif",
    id: "0003",
    name: "air bike",
  },
  {
    bodyPart: "upper legs",
    equipment: "body weight",
    gifUrl: "http://d205bpvrqc9yn1.cloudfront.net/1512.gif",
    id: "1512",
    name: "all fours squad stretch",
  },
  {
    bodyPart: "waist",
    equipment: "body weight",
    gifUrl: "http://d205bpvrqc9yn1.cloudfront.net/0006.gif",
    id: "0006",
    name: "alternate heel touchers",
  },
  {
    bodyPart: "back",
    equipment: "cable",
    gifUrl: "http://d205bpvrqc9yn1.cloudfront.net/0007.gif",
    id: "0007",
    name: "alternate lateral pulldown",
  },
  {
    bodyPart: "lower legs",
    equipment: "body weight",
    gifUrl: "http://d205bpvrqc9yn1.cloudfront.net/1368.gif",
    id: "1368",
    name: "ankle circles",
  },
  {
    bodyPart: "back",
    equipment: "body weight",
    gifUrl: "http://d205bpvrqc9yn1.cloudfront.net/3293.gif",
    id: "3293",
    name: "archer pull up",
  },
  {
    bodyPart: "chest",
    equipment: "body weight",
    gifUrl: "http://d205bpvrqc9yn1.cloudfront.net/3294.gif",
    id: "3294",
    name: "archer push up",
  },
  {
    bodyPart: "waist",
    equipment: "body weight",
    gifUrl: "http://d205bpvrqc9yn1.cloudfront.net/2355.gif",
    id: "2355",
    name: "arm slingers hanging bent knee legs",
  },
  {
    bodyPart: "waist",
    equipment: "body weight",
    gifUrl: "http://d205bpvrqc9yn1.cloudfront.net/2333.gif",
    id: "2333",
    name: "arm slingers hanging straight legs",
  },
  {
    bodyPart: "upper legs",
    equipment: "body weight",
    gifUrl: "http://d205bpvrqc9yn1.cloudfront.net/3214.gif",
    id: "3214",
    name: "arms apart circular toe touch (male)",
  },
  {
    bodyPart: "waist",
    equipment: "body weight",
    gifUrl: "http://d205bpvrqc9yn1.cloudfront.net/3204.gif",
    id: "3204",
    name: "arms overhead full sit-up (male)",
  },
  {
    bodyPart: "chest",
    equipment: "leverage machine",
    gifUrl: "http://d205bpvrqc9yn1.cloudfront.net/0009.gif",
    id: "0009",
    name: "assisted chest dip (kneeling)",
  },
  {
    bodyPart: "waist",
    equipment: "assisted",
    gifUrl: "http://d205bpvrqc9yn1.cloudfront.net/0011.gif",
    id: "0011",
    name: "assisted hanging knee raise",
  },
  {
    bodyPart: "waist",
    equipment: "assisted",
    gifUrl: "http://d205bpvrqc9yn1.cloudfront.net/0010.gif",
    id: "0010",
    name: "assisted hanging knee raise with throw down",
  },
  {
    bodyPart: "lower legs",
    equipment: "assisted",
    gifUrl: "http://d205bpvrqc9yn1.cloudfront.net/1708.gif",
    id: "1708",
    name: "assisted lying calves stretch",
  },
  {
    bodyPart: "upper legs",
    equipment: "assisted",
    gifUrl: "http://d205bpvrqc9yn1.cloudfront.net/1709.gif",
    id: "1709",
    name: "assisted lying glutes stretch",
  },
];

const DataDb = () => {
  return "hello";
};

export default DataDb;
